In [1]:
import numpy as np
import pandas as pd

In [2]:
# tidy up esol datasets
# use Delaney's dataset first
# from: ESOL:  Estimating Aqueous Solubility Directly from Molecular Structure
#       John S. Delaney
#       Journal of Chemical Information and Computer Sciences 2004 44 (3), 1000-1005
#       DOI: 10.1021/ci034243x 

# specifically this website: https://pubs.acs.org/doi/suppl/10.1021/ci034243x/suppl_file/ci034243xsi20040112_053635.txt

In [3]:
delaney = pd.read_csv('esol_delaney.csv')

In [4]:
# check if we can parse all SMILES using rdkit
from rdkit.Chem import MolFromSmiles, MolToSmiles

#delaney['mol'] = delaney.SMILES.apply(MolFromSmiles)
delaney['nonstereo_aromatic_smiles'] = delaney.SMILES.apply(lambda x: MolToSmiles(MolFromSmiles(x), isomericSmiles=False, canonical=True))

In [5]:
# no errors, so we can continue

In [6]:
delaney.shape

(1144, 5)

In [7]:
delaney.nonstereo_aromatic_smiles.drop_duplicates().shape

(1115,)

In [8]:
delaney = delaney.drop_duplicates(subset='nonstereo_aromatic_smiles')

In [9]:
delaney = delaney.rename(columns={'measured log(solubility:mol/L)': 'solubility'})

In [10]:
delaney = delaney[['nonstereo_aromatic_smiles', 'solubility']]

In [11]:
delaney

                        nonstereo_aromatic_smiles  solubility
0                                  ClCC(Cl)(Cl)Cl      -2.180
1                                    CC(Cl)(Cl)Cl      -2.000
2                                  ClC(Cl)C(Cl)Cl      -1.740
3                                      ClCC(Cl)Cl      -1.480
4                             FC(F)(Cl)C(F)(Cl)Cl      -3.040
...                                           ...         ...
1139                   CNC(=O)C(C)SCCSP(=O)(OC)OC       1.144
1140        C=CC1(C)OC(=O)N(c2cc(Cl)cc(Cl)c2)C1=O      -4.925
1141        CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O      -3.893
1142  Cc1cccc(C)c1NC(=O)c1cc(S(N)(=O)=O)c(Cl)cc1O      -3.790
1143                       CNC(=O)Oc1cc(C)cc(C)c1      -2.581

[1115 rows x 2 columns]

In [12]:
delaney.to_csv('regression/esol_delaney.csv', index=False)

In [13]:
# now work on Mobley's database
# v 0.51
# https://escholarship.org/uc/item/6sd403pz
# from: Mobley, D.L., Guthrie, J.P. FreeSolv: a database of experimental and calculated hydration free energies, with input files. J Comput Aided Mol Des 28, 711–720 (2014). https://doi.org/10.1007/s10822-014-9747-x

In [14]:
mobley = pd.read_csv('mobley_database.txt', delimiter=';', header=2)

In [15]:
mobley['nonstereo_aromatic_smiles'] = mobley[' SMILES'].apply(lambda x: MolToSmiles(MolFromSmiles(x), isomericSmiles=False, canonical=True))

In [16]:
mobley.shape

(643, 11)

In [17]:
mobley = mobley.drop_duplicates(subset='nonstereo_aromatic_smiles')
mobley.shape

(639, 11)

In [18]:
mobley = mobley.rename(columns={' experimental value (kcal/mol)': 'solubility'})

In [19]:
mobley = mobley[['nonstereo_aromatic_smiles', 'solubility']]

In [20]:
mobley.head()

               nonstereo_aromatic_smiles  solubility
0                           CCCCCC(=O)OC       -2.49
1                                  CCCCO       -4.72
2  Clc1ccc(-c2cc(Cl)c(Cl)c(Cl)c2Cl)cc1Cl       -3.04
3                              NC1CCCCC1       -4.59
4                           O=COc1ccccc1       -3.82

In [21]:
mobley.to_csv('regression/solubility_mobley.csv', index=False)