In [1]:
import numpy
import pandas as pd

In [2]:
# From:
# In silico Prediction of Chemical Ames Mutagenicity
# Congying Xu, Feixiong Cheng, Lei Chen, Zheng Du, Weihua Li, Guixia Liu, Philip W. Lee, and Yun Tang
# Journal of Chemical Information and Modeling 2012 52 (11), 2840-2847
# DOI: 10.1021/ci300400a

In [3]:
mut = pd.read_excel('mutagenicity.xls', header=1)

In [4]:
# generate nonstereo_aromatic_smiles
from rdkit.Chem import MolFromSmiles, MolToSmiles

def get_canonical_SMILES(smiles):
    try:
        mol = MolFromSmiles(smiles)
    except:
        return False
    if mol is None:
        return False
    return MolToSmiles(mol, canonical=True)

mut['nonstereo_aromatic_smiles'] = mut.SMILES.apply(get_canonical_SMILES)

[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 3 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 6 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 17 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 25 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 20 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 2 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 10 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 19 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 15 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 10 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 19 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 25 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 16 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 15 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 17 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 10 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 30 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 3 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 5, is greater than permitted
[11:50:35] Explicit valence for atom # 10 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 10 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 18 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 6 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 30 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 27 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 3 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 2 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 17 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 12 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 6 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 10 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 16 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 19 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 12 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 15 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 6 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 10 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 4 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 10 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 16 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 17 N, 5, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 2 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 5, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 16 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 4 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 5, is greater than permitted
[11:50:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 6 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 13 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 16 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 2 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 4 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 4 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 4 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 4 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 4 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 5 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 11 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 4 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 8 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 3 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 9 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 4 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 10 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 7 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 14 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 22 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 0 N, 4, is greater than permitted
[11:50:35] Explicit valence for atom # 1 N, 4, is greater than permitted

In [5]:
mut.loc[mut.nonstereo_aromatic_smiles == False].shape

(339, 3)

In [6]:
mut = mut.loc[mut.nonstereo_aromatic_smiles != False]

In [7]:
mut.shape

(7278, 3)

In [8]:
mut = mut.drop_duplicates(subset='nonstereo_aromatic_smiles')

In [9]:
mut.head()

,SMILES,Labels,nonstereo_aromatic_smiles
0,[O-][N+](=O)c1ccc2ccc3ccc(c4c5ccccc5c1c2c34)[N...,mutagens,O=[N+]([O-])c1ccc2ccc3ccc([N+](=O)[O-])c4c5ccc...
1,[O-][N+](=O)c1c2CCCCc2c3ccc4cccc5ccc1c3c45,mutagens,O=[N+]([O-])c1c2c(c3ccc4cccc5ccc1c3c45)CCCC2
2,O=C1c2ccccc2C(=O)c3c1ccc4c3[nH]c5c6C(=O)c7cccc...,non-mutagens,O=c1c2ccccc2c(=O)c2c1ccc1c2[nH]c2c3c(=O)c4cccc...
3,NNC(=O)CNC(=O)C=N#N,mutagens,[N-]=[N+]=CC(=O)NCC(=O)NN
4,O=C1NC(=O)C(C=N1)=N#N,mutagens,[N-]=[N+]=C1C=NC(=O)NC1=O

In [10]:
mut = mut.replace({"mutagens": 1, 'non-mutagens': 0})

/tmp/ipykernel_14362/1169322640.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  mut = mut.replace({"mutagens": 1, 'non-mutagens': 0})

In [11]:
mut = mut.rename(columns={'Labels': 'mutagenicity'})

In [12]:
mut = mut[['nonstereo_aromatic_smiles', 'mutagenicity']]

In [15]:
mut.to_csv('classification/mutagenicity.csv', index=False)
mut.shape

(7255, 2)

In [16]:
mut.head()

                           nonstereo_aromatic_smiles  mutagenicity
0  O=[N+]([O-])c1ccc2ccc3ccc([N+](=O)[O-])c4c5ccc...             1
1       O=[N+]([O-])c1c2c(c3ccc4cccc5ccc1c3c45)CCCC2             1
2  O=c1c2ccccc2c(=O)c2c1ccc1c2[nH]c2c3c(=O)c4cccc...             0
3                          [N-]=[N+]=CC(=O)NCC(=O)NN             1
4                          [N-]=[N+]=C1C=NC(=O)NC1=O             1

In [14]:
# now a new dataset from:
    # Benchmark Data Set for in Silico Prediction of Ames Mutagenicity
    # Katja Hansen, Sebastian Mika, Timon Schroeter, Andreas Sutter, Antonius ter Laak, Thomas Steger-Hartmann, Nikolaus Heinrich, and Klaus-Robert Müller
    # Journal of Chemical Information and Modeling 2009 49 (9), 2077-2081
    # DOI: 10.1021/ci900161g
# downloaded and left unchanged

In [28]:
mut2 = pd.read_csv('ci900161g_si_001/smiles_cas_N6512.smi', delimiter='\t', header=None)
mut2.head()

                                                   0             1  2
0  O=C1c2ccccc2C(=O)c3c1ccc4c3[nH]c5c6C(=O)c7cccc...    2475-33-4   0
1                             NNC(=O)CNC(=O)\C=N\#N      820-75-7   1
2                          O=C1NC(=O)\C(=N/#N)\C=N1     2435-76-9   1
3                              NC(=O)CNC(=O)\C=N\#N      817-99-2   1
4            CCCCN(CC(O)C1=C\C(=N/#N)\C(=O)C=C1)N=O   116539-70-9   1

In [29]:
mut2['nonstereo_aromatic_smiles'] = mut2[0].apply(get_canonical_SMILES)
mut2.shape

[11:57:41] SMILES Parse Error: syntax error while parsing: NNC(=O)CNC(=O)\C=N\#N
[11:57:41] SMILES Parse Error: check for mistakes around position 20:
[11:57:41] NNC(=O)CNC(=O)\C=N\#N
[11:57:41] ~~~~~~~~~~~~~~~~~~~~^
[11:57:41] SMILES Parse Error: Failed parsing SMILES 'NNC(=O)CNC(=O)\C=N\#N' for input: 'NNC(=O)CNC(=O)\C=N\#N'
[11:57:41] SMILES Parse Error: syntax error while parsing: O=C1NC(=O)\C(=N/#N)\C=N1
[11:57:41] SMILES Parse Error: check for mistakes around position 17:
[11:57:41] O=C1NC(=O)\C(=N/#N)\C=N1
[11:57:41] ~~~~~~~~~~~~~~~~^
[11:57:41] SMILES Parse Error: extra open parentheses while parsing: O=C1NC(=O)\C(=N/#N)\C=N1
[11:57:41] SMILES Parse Error: check for mistakes around position 13:
[11:57:41] O=C1NC(=O)\C(=N/#N)\C=N1
[11:57:41] ~~~~~~~~~~~~^
[11:57:41] SMILES Parse Error: Failed parsing SMILES 'O=C1NC(=O)\C(=N/#N)\C=N1' for input: 'O=C1NC(=O)\C(=N/#N)\C=N1'
[11:57:41] SMILES Parse Error: syntax error while parsing: NC(=O)CNC(=O)\C=N\#N
[11:57:41] SMILES Parse Error: check for mistakes around position 19:
[11:57:41] NC(=O)CNC(=O)\C=N\#N
[11:57:41] ~~~~~~~~~~~~~~~~~~^
[11:57:41] SMILES Parse Error: Failed parsing SMILES 'NC(=O)CNC(=O)\C=N\#N' for input: 'NC(=O)CNC(=O)\C=N\#N'
[11:57:41] SMILES Parse Error: syntax error while parsing: CCCCN(CC(O)C1=C\C(=N/#N)\C(=O)C=C1)N=O
[11:57:41] SMILES Parse Error: check for mistakes around position 22:
[11:57:41] CCCN(CC(O)C1=C\C(=N/#N)\C(=O)C=C1)N=O
[11:57:41] ~~~~~~~~~~~~~~~~~~~~^
[11:57:41] SMILES Parse Error: extra open parentheses while parsing: CCCCN(CC(O)C1=C\C(=N/#N)\C(=O)C=C1)N=O
[11:57:41] SMILES Parse Error: check for mistakes around position 6:
[11:57:41] CCCCN(CC(O)C1=C\C(=N/#N)\C(=O)C=C1)N=O
[11:57:41] ~~~~~^
[11:57:41] SMILES Parse Error: extra open parentheses while parsing: CCCCN(CC(O)C1=C\C(=N/#N)\C(=O)C=C1)N=O
[11:57:41] SMILES Parse Error: check for mistakes around position 18:
[11:57:41] CCCCN(CC(O)C1=C\C(=N/#N)\C(=O)C=C1)N=O
[11:57:41] ~~~~~~~~~~~~~~~~~^
[11:57:41] SMILES Parse Error: Failed parsing SMILES 'CCCCN(CC(O)C1=C\C(=N/#N)\C(=O)C=C1)N=O' for input: 'CCCCN(CC(O)C1=C\C(=N/#N)\C(=O)C=C1)N=O'
[11:57:41] SMILES Parse Error: syntax error while parsing: NC(COC(=O)\C=N/#N)C(=O)O
[11:57:41] SMILES Parse Error: check for mistakes around position 16:
[11:57:41] NC(COC(=O)\C=N/#N)C(=O)O
[11:57:41] ~~~~~~~~~~~~~~~^
[11:57:41] SMILES Parse Error: extra open parentheses while parsing: NC(COC(=O)\C=N/#N)C(=O)O
[11:57:41] SMILES Parse Error: check for mistakes around position 3:
[11:57:41] NC(COC(=O)\C=N/#N)C(=O)O
[11:57:41] ~~^
[11:57:41] SMILES Parse Error: Failed parsing SMILES 'NC(COC(=O)\C=N/#N)C(=O)O' for input: 'NC(COC(=O)\C=N/#N)C(=O)O'
[11:57:41] SMILES Parse Error: syntax error while parsing: CCN(CC(O)C1=CC(=O)\C(=N\#N)\C=C1)N=O
[11:57:41] SMILES Parse Error: check for mistakes around position 25:
[11:57:41] CC(O)C1=CC(=O)\C(=N\#N)\C=C1)N=O
[11:57:41] ~~~~~~~~~~~~~~~~~~~~^
[11:57:41] SMILES Parse Error: extra open parentheses while parsing: CCN(CC(O)C1=CC(=O)\C(=N\#N)\C=C1)N=O
[11:57:41] SMILES Parse Error: check for mistakes around position 4:
[11:57:41] CCN(CC(O)C1=CC(=O)\C(=N\#N)\C=C1)N=O
[11:57:41] ~~~^
[11:57:41] SMILES Parse Error: extra open parentheses while parsing: CCN(CC(O)C1=CC(=O)\C(=N\#N)\C=C1)N=O
[11:57:41] SMILES Parse Error: check for mistakes around position 21:
[11:57:41] CCN(CC(O)C1=CC(=O)\C(=N\#N)\C=C1)N=O
[11:57:41] ~~~~~~~~~~~~~~~~~~~~^
[11:57:41] SMILES Parse Error: Failed parsing SMILES 'CCN(CC(O)C1=CC(=O)\C(=N\#N)\C=C1)N=O' for input: 'CCN(CC(O)C1=CC(=O)\C(=N\#N)\C=C1)N=O'

(6512, 4)

In [30]:
mut2 = mut2.loc[mut2.nonstereo_aromatic_smiles != False]
mut2.shape

(6506, 4)

In [31]:
mut2 = mut2.drop_duplicates(subset='nonstereo_aromatic_smiles')
mut2.shape

(6505, 4)

In [32]:
mut2.head()

,0,1,2,nonstereo_aromatic_smiles
0,O=C1c2ccccc2C(=O)c3c1ccc4c3[nH]c5c6C(=O)c7cccc...,2475-33-4,0,O=c1c2ccccc2c(=O)c2c1ccc1c2[nH]c2c3c(=O)c4cccc...
7,CC(=O)OC1(CCC2C3C=C(Cl)C4=CC(=O)OCC4(C)C3CCC12...,105149-00-6,0,CC(=O)OC1(C(C)=O)CCC2C3C=C(Cl)C4=CC(=O)OCC4(C)...
8,Nc1nc(N)nc(N)n1,108-78-1,0,Nc1nc(N)nc(N)n1
9,Cc1ccc(N=Nc2c(O)ccc3ccccc23)c(c1)[N+](=O)[O-],2425-85-6,1,Cc1ccc(N=Nc2c(O)ccc3ccccc23)c([N+](=O)[O-])c1
10,CC(C)CC(=O)Nc1snc2ccccc12,67019-24-3,0,CC(C)CC(=O)Nc1snc2ccccc12

In [33]:
mut2 = mut2.rename(columns={2: 'mutagenicity'})
mut2.head()

,0,1,mutagenicity,nonstereo_aromatic_smiles
0,O=C1c2ccccc2C(=O)c3c1ccc4c3[nH]c5c6C(=O)c7cccc...,2475-33-4,0,O=c1c2ccccc2c(=O)c2c1ccc1c2[nH]c2c3c(=O)c4cccc...
7,CC(=O)OC1(CCC2C3C=C(Cl)C4=CC(=O)OCC4(C)C3CCC12...,105149-00-6,0,CC(=O)OC1(C(C)=O)CCC2C3C=C(Cl)C4=CC(=O)OCC4(C)...
8,Nc1nc(N)nc(N)n1,108-78-1,0,Nc1nc(N)nc(N)n1
9,Cc1ccc(N=Nc2c(O)ccc3ccccc23)c(c1)[N+](=O)[O-],2425-85-6,1,Cc1ccc(N=Nc2c(O)ccc3ccccc23)c([N+](=O)[O-])c1
10,CC(C)CC(=O)Nc1snc2ccccc12,67019-24-3,0,CC(C)CC(=O)Nc1snc2ccccc12

In [34]:
mut2 = mut2[['nonstereo_aromatic_smiles', 'mutagenicity']]

In [35]:
mut2.to_csv('classification/Hansen.csv', index=False)